// ManifoldGen — Generator context and shared types

namespace ManifoldGen;

/// <summary>Shared state passed to all emitters.</summary>
public sealed class GeneratorContext
{
    public SteamApiModel Model    { get; }
    public Dictionary<string, int> PackMap { get; }

    // SDK version is embedded in the output file headers
    public string SdkVersion { get; } = "1.64";
    public string GenVersion  { get; } = "1.0.0";

    public GeneratorContext(SteamApiModel model, Dictionary<string, int> packMap)
    {
        Model   = model;
        PackMap = packMap;
    }

    /// <summary>Standard file header comment for all generated files.</summary>
    public string FileHeader(string filename) =>
        $"""
        // AUTO-GENERATED by ManifoldGen {GenVersion} from steam_api.json SDK {SdkVersion}. DO NOT EDIT.
        // Source: Steamworks SDK {SdkVersion} — steam_api.json + header pack pragmas
        // File:   {filename}
        //
        // To regenerate: ManifoldGen <path/to/steam_api.json> <output_dir>

        """;
}

/// <summary>Records a construct that was skipped during generation.</summary>
public sealed record SkippedItem(string Category, string Name, string Reason);

/// <summary>Contract for all code emitters.</summary>
public interface IEmitter
{
    string OutputFileName { get; }
    string Emit(GeneratorContext ctx, List<SkippedItem> skipped);
}
